### ISSUE TITLE
Encountered unknown column type

### ISSUE THREAD

**Issue by victorlcampos** [martijn/xsv#10]
Hi,
I'am try upload a xlsx file and i'm getting a erro on format cell:

"Encountered unknown column type n":["/opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/bundler/gems/xsv-027d612d4f74/lib/xsv/sheet_rows_handler.rb:28:in `format_cell'","/opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/bundler/gems/xsv-027d612d4f74/lib/xsv/sheet_rows_handler.rb:98:in `end_element'","/opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/bundler/gems/xsv-027d612d4f74/lib/xsv/sheet.rb:62:in `sax_parse'","/opt/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/bundler/gems/xsv-027d612d4f74/lib/xsv/sheet.rb:62:in

Can you give me a light to fix it?

**Comment by martijn** [comment]
Absolutely. Can you share a minimal Excel file that causes this exception?

**Comment by martijn** [comment]
@victorlcampos can you test with the `issue-10` branch and see if it returns the data in the correct way?

**Comment by victorlcampos** [comment]
Here is the file:

https://portal.visagio.com/file-sender/download?token=b3c622fe-1ea4-4425-b671-dab982e04c51

**Comment by martijn** [comment]
Thanks for sharing an example.

Ok so the new `issue-10` branch seems to fix the problem. This sheet was generated by LibreOffice which has some quirks that not only affect Xsv but also other Excel readers (and probably Excel itself). Currently this leads to booleans being returned as integer 1/0 by Xsv instead of actual booleans and there is no way for me to fix that.

Let me know if the branch returns the correct results for you and I'll release a new version with the fix.

**Comment by victorlcampos** [comment]
Yes, it works =)

**Comment by martijn** [comment]
Great, I just pushed Xsv 0.3.8 with these changes.
